site_name: 2022 May Common Fund Hackathon

theme:
  name: material
  palette:
    primary: white

docs_dir: ./docs

nav:
    - Home: index.md
    - Session Details and Recordings: about.md
    - Continued CFDE Engagement: engage.md
    - Code of Conduct: CODEOFCONDUCT.md
    - Contributing: CONTRIBUTING.md
    - License: LICENSE.md
